---
apiVersion: cloudbees.com/v2025.12
kind: microservice
metadata:
  name: qe microservice name2
spec:
  definitionSource: git
  definitionSourceParameters:
    - branch: test
    - config: config
    - repoUrl: test
  definitionType: helm
  deployParameters:
    - chart: test
    - releaseName: test
  rollbackParameters:
    - rollbackEnabled: "false"
    - waitTimeout: "300"
