---
apiVersion: cloudbees.com/v2025.12
kind: component
metadata:
  name: qe filesysrepo master component
  description: JIi4JCZZ2R55L18v0p9I37ohQFJKR1tp8BTbw6JY6zFCZRePbpQOWG25JD2l4WpcspM6voWOTOzyFDbFTBjslZnPsTo7EVUl1cjBZti6v22VPL2laOUiOQpwdmuqBYmrXtWhDRikvjjgkJDz6uMjgV2RfGsRa0lqZrgjqdQ0VUr2c9bXHfw5GlO5jRs1l83RCZCCPgtH4wSXouiQWQ8eF2wvt2w67PbeKrEParRdUrm7ILJ2NaRA0ptJDFyitUUpf2jM6znv9cU7cfTSVkwr5PSczHWKydtsDaFiTuM1wKfV3rV1md1SPecHcztVAXCYq8dvDQ5JeLAOqLEYIwU47dY7q6JCN42iQUx2kksryBazARCsOOjEiaQLRHKCSxvbzixx959U1QML1ijJ
spec:
  pluginKey: EC-FileSysRepo
