---
apiVersion: cloudbees.com/v2025.12
kind: process
metadata:
  name: component process
  description: Automation backend tests
spec:
  processType: DEPLOY
  processSteps:
    - name: qe step 1
      actualParameters:
        - commandToRun: "{% cb_include_as_yaml_comment 'processSteps/qe step 1.cmd' %}"
      dependencyJoinType: and
      processStepType: command
      subprocedure: RunCommand
      subproject: /plugins/EC-Core/project
    - name: qe step 2
      actualParameters:
        - commandToRun: "{% cb_include_as_yaml_comment 'processSteps/qe step 2.cmd' %}"
      dependencyJoinType: and
      processStepType: command
      subprocedure: RunCommand
      subproject: /plugins/EC-Core/project
    - name: qe step 3
      actualParameters:
        - commandToRun: "{% cb_include_as_yaml_comment 'processSteps/qe step 3.cmd' %}"
      dependencyJoinType: and
      processStepType: command
      subprocedure: RunCommand
      subproject: /plugins/EC-Core/project
