---
apiVersion: cloudbees.com/v2025.12
kind: component
metadata:
  name: qe nexus master component
spec:
  reference: true
  sourceComponentName: qe nexus master component
  sourceProjectName: qe proj nameGenerateApplyDslSyncForComponentshzEHG
