---
apiVersion: cloudbees.com/v2025.12
kind: process
metadata:
  name: application process
  description: Automation backend tests
spec:
  exclusiveEnvironment: false
  processType: DEPLOY
  formalParameters:
    - name: ec_enforceDependencies
      defaultValue: "0"
      expansionDeferred: true
      type: checkbox
  processSteps:
    - name: qe step 1
      actualParameters:
        - commandToRun: "{% cb_include_as_yaml_comment 'processSteps/qe step 1.cmd' %}"
      applicationTierName: qe tier name
      dependencyJoinType: and
      processStepType: command
      subprocedure: RunCommand
      subproject: /plugins/EC-Core/project
      properties:
        - name: ec_deploy
          properties:
            - name: ec_notifierStatus
              value: "0"
    - name: qe step 2
      actualParameters:
        - commandToRun: "{% cb_include_as_yaml_comment 'processSteps/qe step 2.cmd' %}"
      applicationTierName: qe tier name
      dependencyJoinType: and
      processStepType: command
      subprocedure: RunCommand
      subproject: /plugins/EC-Core/project
      properties:
        - name: ec_deploy
          properties:
            - name: ec_notifierStatus
              value: "0"
    - name: qe step 3
      actualParameters:
        - commandToRun: "{% cb_include_as_yaml_comment 'processSteps/qe step 3.cmd' %}"
      applicationTierName: qe tier name
      dependencyJoinType: and
      processStepType: command
      subprocedure: RunCommand
      subproject: /plugins/EC-Core/project
      properties:
        - name: ec_deploy
          properties:
            - name: ec_notifierStatus
              value: "0"
